server:
  port: 21010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:22000
        fail-fast: false
        prefer-open-api: true
        watch-delay: 30000
        timeout: 30000