server:
  port: 22010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:22000   # Nacos 注册中心地址
      config:
        server-addr: 127.0.0.1:22000   # Nacos 配置中心地址
        namespace: public             # 可以自定义namespace
        group: DEFAULT_GROUP          # 配置分组
        file-extension: yaml          # 配置文件格式
        name: ${spring.application.name}-config  # 配置文件名示例

    gateway:
      routes:
        # 示例路由配置，根据实际服务进行调整
        - id: service-example
          uri: lb://service-example
          predicates:
            - Path=/api/example/**
          filters:
            - StripPrefix=2